name: job.yml

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.REPOSITORY}}
    - name: Run ML job 
      run: az ml job create --file job.yml -w "mlw-dp100-labs" -g "rg-dp100-labs"


