name: Code checks

# Trigger the workflow on workflow_dispatch event (manual trigger)
on:
  workflow_dispatch:

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out repo
      uses: actions/checkout@v2

    # Set up Python 3.8
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    # Install Flake8 for linting
    - name: Install Flake8
      run: |
        python -m pip install flake8

    # Run linting tests on the src/model directory
    - name: Run linting tests
      run: |
        flake8 src/model/
