name: Pull Request Workflow

on: 
  pull_request: 
    branches: 
      - main

jobs: 
  verify-code: 
    runs-on: ubuntu-latest

    steps: 
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Echo placeholder step
      run: echo "This is a placeholder step for code verification"
